apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: howz9jco0-dotnet-basic
  janus-idp.io/tekton: howz9jco0-dotnet-basic
  backstage.io/kubernetes-id: howz9jco0-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: howz9jco0-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
